// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vjidsgkrofxrqquknkut.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZqaWRzZ2tyb2Z4cnFxdWtua3V0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQ2NTcxNTcsImV4cCI6MjA3MDIzMzE1N30.ksf7ty_ZiUlIXM6P8_L3JyqZLXscUxGGOPscrFKzAp4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});